# Generated by Django 3.2.25 on 2024-07-26 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0002_auto_20240726_1932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='image',
        ),
    ]
