# Generated by Django 3.2.25 on 2024-07-26 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_remove_service_rating'),
        ('packages', '0003_remove_package_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='services',
            field=models.ManyToManyField(related_name='packages', to='services.Service'),
        ),
    ]
