# Generated by Django 3.2.25 on 2024-07-27 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0004_package_services'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='package',
            options={'ordering': ['name'], 'verbose_name_plural': 'Packages'},
        ),
    ]
