# Generated by Django 3.2.25 on 2024-06-25 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20240625_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='available_dates',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='service',
            name='available_times',
            field=models.JSONField(default=dict),
        ),
    ]
