# Generated by Django 3.2.25 on 2024-07-26 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_auto_20240708_1833'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='rating',
        ),
    ]
