# Generated by Django 3.2.25 on 2024-07-26 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['service'], name='reviews_rev_service_1b4478_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['package'], name='reviews_rev_package_21dfcc_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['rating'], name='reviews_rev_rating_2db6dd_idx'),
        ),
    ]
